apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cims-clinicalnote-v1-svc-virtual-svc
spec:
  hosts:
  - cims-clinicalnote-v1-svc
  http:
  - match:
    - headers:
        serviceCode:
          exact: SPP
    route: 
    - destination:
        host: cims-clinicalnote-v1-svc
        subset: v1
  - match:
    - headers:
        serviceCode:
          exact: FCS 
    route:
    - destination:
        host: cims-clinicalnote-v1-svc
        subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cims-clinicalnote-v1-svc-dest-rule
spec:
  host: cims-clinicalnote-v1-svc
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2 
