apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app
    version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: 1.0.0
  template:
    metadata:
      labels:
        app: app
        version: 1.0.0
    spec:
      serviceAccount: istiosrv
      containers:
      - name: app
        image: registry.cn-hangzhou.aliyuncs.com/shenkonghui/app
        env:
        - name: version
          value: v1
        ports:
        - containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: app
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - name: http
    port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels:
    app: app
    version: 2.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: 2.0.0
  template:
    metadata:
      labels:
        app: app
        version: 2.0.0
    spec:
      serviceAccount: istiosrv
      containers:
      - name: app
        image: registry.cn-hangzhou.aliyuncs.com/shenkonghui/app
        env:
        - name: version
          value: v2
        ports:
        - containerPort: 8080
          protocol: TCP
