apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  labels:
    app: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: app
        image: registry.cn-hangzhou.aliyuncs.com/shenkonghui/app
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app-v1
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
    app: app
    version: v1
  ports:
  - name: app
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
  labels:
    app: app
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v2
  template:
    metadata:
      labels:
        app: app
        version: v2
    spec:
      containers:
      - name: app
        image: registry.cn-hangzhou.aliyuncs.com/shenkonghui/app
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: app-v2
  labels:
    app: app
spec:
  type: ClusterIP
  selector:
    app: app
    version: v2
  ports:
  - name: app
    port: 80
